### PR TITLE
fix: accessing nested object properties by reference

### LINKED ISSUE #86: Bug: failed to resolve a reference to inner property of an another reference
## Steps To Reproduce

Failed to resolve the references following:

```yaml
components:
  schemas:
    Foo: 
      type: object
      properties:
        bar:
          type: object
          properties:
            baz:
              type: string
    Bar:
      $ref: '#/components/schemas/Foo/properties/bar'
    Baz:
      $ref: '#/components/schemas/Bar/properties/baz' # failed!
```

## The current behavior

```
/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/Guard.ts:58
  return !!schema.oneOf && typeof schema.oneOf !== "boolean" && Array.isArray(schema.oneOf);
                  ^
TypeError: Cannot read properties of undefined (reading 'oneOf')
    at Object.isOneOfSchema (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/Guard.ts:58:19)
    at Object.convert (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/toTypeNode.ts:129:13)
    at createTypeNode (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/components/Schemas.ts:43:29)
    at /Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/components/Schemas.ts:51:19
    at Array.forEach (<anonymous>)
    at Object.generateNamespace (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/components/Schemas.ts:30:27)
    at Parser.initialize (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/Parser.ts:41:17)
    at new Parser (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/internal/OpenApiTools/Parser.ts:33:10)
    at CodeGenerator.createParser (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/index.ts:32:12)
    at new CodeGenerator (/Users/karupanerura/src/github.com/karupanerura/openapi-typescript-code-generator/src/index.ts:27:24)
```

## The expected behavior

No error to resolve the reference`Baz`.

### PR DESCRIPTION
**Pull request by Himenon**
## Summary

close #86

### CODE REVIEW

File: src/internal/OpenApiTools/TypeNodeContext.ts [hunk 1]
```diff
@@ -93,6 +96,27 @@ export const create = (
...
+  const findSchemaByPathArray = (
+    pathArray: string[],
+    remainPathArray: string[] = [],
+  ): OpenApi.Schema | OpenApi.Reference | OpenApi.JSONSchemaDefinition => {
+    const schema = DotProp.get<OpenApi.Schema>(rootSchema, pathArray.join("."));
+    if (!schema) {
+      return findSchemaByPathArray(pathArray.slice(0, pathArray.length - 1), [pathArray[pathArray.length - 1], ...remainPathArray]);
+    }
+    if (Guard.isReference(schema)) {
+      const ref = Reference.generate(entryPoint, entryPoint, schema);
```
Comment (Himenon) [inline src/internal/OpenApiTools/TypeNodeContext.ts:108]: Perhaps it could be broken during REMOTE REFERENCE.
